version: '3.8'

services:
  # Production frontend configuration
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: coaching-app-frontend-prod
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
      NODE_ENV: production
    ports:
      - "80:80"
    volumes: []  # Remove development volumes
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      timeout: 10s
      retries: 5
      interval: 15s
      start_period: 30s

  # Production backend configuration
  backend:
    environment:
      GIN_MODE: release
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASSWORD: apppassword
      DB_NAME: coaching_app
      SERVER_PORT: 8080

  # Production database configuration
  database:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: coaching_app
      MYSQL_USER: ${MYSQL_USER:-appuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-apppassword}